### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by thanhtrixx** [thanhtrixx/ruby-on-rails-coderschool#1]
Deployed to Heroku
![heroku](https://cloud.githubusercontent.com/assets/689776/15900715/b1b2b4ac-2dca-11e6-8e3b-f69e3a8617b5.JPG)
but when goto https://frozen-everglades-25877.herokuapp.com/ show error

**Comment by hoksilato** [comment]
Hi @thanhtrixx 

You can go to this url https://frozen-everglades-25877.herokuapp.com/articles. And for fixing your issue, you can set the `root` path in `config/routes.rb` to `articles#index`.

And could you please update your `README.md` with the template we provided in pre-work instruction. Thanks.

We are happy to answer any questions you have (by commenting here or emailing to ruby@coderschool.vn).

/cc @coderschoolreview

**Comment by thanhtrixx** [comment]
Hi @hoksilato,
Tks for your support! I'll update README.md file.
/cc @coderschoolreview

**Comment by thanhtrixx** [comment]
Fixed
